### ISSUE TITLE
Take off must be called before shared()

### ISSUE THREAD

**Issue by gonzalovinas** [urbanairship/urbanairship-cordova#244]
Hi there

I've to format my linux box and reinstall everything (almost transparentlly). Every cordova app I had is working OK, but the only one I have with UrbanAirship doesn't work at all, because at start it throws out-of-no-change at all before format my box:

  Caused by: java.lang.IllegalStateException: Take off must be called before shared()
        at com.urbanairship.UAirship.shared(UAirship.java:151)
        at com.urbanairship.cordova.UAirshipPluginManager.checkOptInStatus(UAirshipPluginManager.java:125)
        at com.urbanairship.cordova.UAirshipPlugin.onResume(UAirshipPlugin.java:127)
        at org.apache.cordova.PluginManager.onResume(PluginManager.java:264)
        at org.apache.cordova.CordovaWebViewImpl.handleResume(CordovaWebViewImpl.java:448)
        at org.apache.cordova.CordovaActivity.onResume(CordovaActivity.java:275)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
        at android.app.Activity.performResume(Activity.java:6766)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3377)

**Comment by rlepinski** [comment]
@gonzalovinas What cordova version are you  using?

**Comment by gonzalovinas** [comment]
cordova 8.0.0 and cordova-android 6.3.0 as previously used before I formatted my linux box...

**Comment by rlepinski** [comment]
do you have any other logs? I am pretty sure its due to missing config

**Comment by gonzalovinas** [comment]
Full logcat above. Symtom is app lauch crashes. No splashscreen neither. What else could I bring to you?

http://pasted.co/40549c02

**Comment by gonzalovinas** [comment]
My bad! somehow AndroidManifest.xml was modified by a **cordova clean** and then **cordova build** re-write it from factory configuration skipping custom "edition". 

🙏🙏🙏🙏🙏🙏🙏

I'm very sorry. Thanks for the "autopilot"  tip.

**Comment by rlepinski** [comment]
No problem. Glad you figured it out
