### ISSUE TITLE
Invalid GCM Sender Id

### ISSUE THREAD

**Issue by shreyasb0912** [urbanairship/urbanairship-cordova#250]
Hello,

I am using this plugin in my Phonegap application to implement FCM. But I am facing issues while registering my device with the FCM server as it throws INVALID_SENDER error. 

Could anyone please help me in resolving this issue.

Please refer to the logs for complete information.

Thanks,
Shreyas Bhondve

# Preliminary Info

### What version of urbanairship-cordova are you using?
ℹ urbanairship-cordova v6.4.0

### Is your issue affecting the Android platform, iOS platform, or both?
ℹ Android

### What version of cordova-ios and/or cordova-android are you using?
ℹ Cordova 8.0.0

# Report

### What unexpected behavior are you seeing?
ℹ The plugin is not able to register to the FCM server and throwing error INVALID_SENDER.

### What is the expected behavior?
ℹ Application should successfully register the device to the FCM server and receive notifications. 

### What are the steps to reproduce the unexpected behavior?
ℹ Add plugin to the Cordova application. Specify the App key, App secret key and GCM Sender id in the config.xml. Run the Android application and check the logs for the error.

### Do you have logging for the issue?
ℹ 08-28 13:12:45.788 3294-3388/com.crosscountry.careercare E/NotificationApp - UALib: Push registration failed.
    com.urbanairship.push.PushProvider$RegistrationException: FCM registration failed.
        at com.urbanairship.push.fcm.FcmPushProvider.getRegistrationToken(FcmPushProvider.java:66)
        at com.urbanairship.push.PushManagerJobHandler.onUpdatePushRegistration(PushManagerJobHandler.java:206)
        at com.urbanairship.push.PushManagerJobHandler.performJob(PushManagerJobHandler.java:123)
        at com.urbanairship.push.PushManager.onPerformJob(PushManager.java:404)
        at com.urbanairship.job.Job$1.run(Job.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.io.IOException: INVALID_SENDER
        at com.google.firebase.iid.zzo.zza(Unknown Source)
        at com.google.firebase.iid.zzo.zza(Unknown Source)
        at com.google.firebase.iid.zzr.then(Unknown Source)
        at com.google.android.gms.tasks.zzd.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818)

**Comment by rlepinski** [comment]
@shreyasb0912 Its a bug in AAPT2 that converts the sender ID string to a number when we parse the config. You can either prefix your sender ID with `sender:` or update to 7.2 of our plugin and remove the sender ID completely and it will pick it up from google-services.json.

**Comment by rlepinski** [comment]
For more info: https://github.com/urbanairship/urbanairship-cordova/issues/206
