### ISSUE TITLE
Push registration failed

### ISSUE THREAD

**Issue by jskrepnek** [urbanairship/urbanairship-cordova#294]
# Preliminary Info

### What version of urbanairship-cordova are you using?
ℹ 7.5.2

### Is your issue affecting the Android platform, iOS platform, or both?
ℹ Android

### What version of cordova-ios and/or cordova-android are you using?
ℹ cordova-android: 7.1.1

### What are the versions of any relevant development tools you are using?
ℹ If applicable, please include any other relevant information about the version of your
IDE, plugin(s), or package manager(s) here.
```
    <plugin name="cordova-android-support-gradle-release" spec="1.4.4">
        <variable name="ANDROID_SUPPORT_VERSION" value="27.+" />
    </plugin>
    <plugin name="cordova-plugin-intercom" spec="6.1.0" />
    <plugin name="cordova-android-play-services-gradle-release" spec="^2.0.0">
        <variable name="PLAY_SERVICES_VERSION" value="15.+" />
    </plugin>
```
# Report

### What unexpected behavior are you seeing?
ℹ FCM registration is failing.

### What is the expected behavior?
ℹ FCM registration and push registration succeeds

### What are the steps to reproduce the unexpected behavior?
ℹ I followed the steps in the Quickstart, using a config.xml for automatic take off.  The google-services.json file was copied as expected to `platforms/android/app`.

### Do you have logging for the issue?
ℹ 

```
019-03-04 11:13:55.423 13706-14293/ca.koho.dev E/KOHO Dev - UALib: Push registration failed.
    com.urbanairship.push.PushProvider$RegistrationException: FCM registration failed.
        at com.urbanairship.push.fcm.FcmPushProvider.getRegistrationToken(FcmPushProvider.java:72)
        at com.urbanairship.push.PushManagerJobHandler.onUpdatePushRegistration(PushManagerJobHandler.java:208)
        at com.urbanairship.push.PushManagerJobHandler.performJob(PushManagerJobHandler.java:125)
        at com.urbanairship.push.PushManager.onPerformJob(PushManager.java:391)
        at com.urbanairship.job.Job$1.run(Job.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: SERVICE_NOT_AVAILABLE
        at com.google.firebase.iid.FirebaseInstanceId.zza(Unknown Source:94)
        at com.google.firebase.iid.FirebaseInstanceId.getToken(Unknown Source:82)

```

**Comment by rlepinski** [comment]
The underlying SDK will automatically retry on SERVICE_NOT_AVAILABLE using exponential backoff. There is not much we can do other than retry. Do you have any devices successfully registering? If so, your set up is probably fine and the device either has network issues or its Google Play Services are out of date.

**Comment by jskrepnek** [comment]
No network issues and this has been persistent so will check on Play Services.  Is there a required version?

**Comment by jskrepnek** [comment]
Sorry for the distraction, that was the issue.
